### ISSUE TITLE
How can i use moment in a formatter?

### ISSUE THREAD

**Issue by mok-liee** [keichi/binary-parser#75]
Hello Team,

can u help me please. How can i use moment in a formatter?

```
const Parser = require("binary-parser").Parser;
const moment = require('moment');

let time = function(timestamp) {
	return moment(timestamp, 'YYMMDDHHmmssSS').format('YYYY-MM-DD HH:mm:ss.SS');
};

let Telegram = new Parser()
	.string('timestamp', {encoding: 'hex', length: 7, formatter: time});

```

The Exception is:

```
evalmachine.<anonymous>:9
        return moment(timestamp, 'YYMMDDHHmmssSS').format('YYYY-MM-DD HH:mm:ss.SS');
        ^

ReferenceError: moment is not defined
    at Parser.<anonymous> (evalmachine.<anonymous>:9:2)
...

```

I think the Problem is that Parser dont know moment. But how can i realize that?

**Comment by ElbowBaggins** [comment]
I know this is probably too late for you, but hopefully it helps someone.

When `Parser` invokes your `formatter`, it does so with `Function.prototype.apply()` and passes itself as the `this` argument. As a result, the function is now running in the context of the `Parser` and not the lexical context that you are expecting.

I addressed this by adding a `$imports` property to `Parser.prototype` where one could add anything they'd like to make available from within the `Parser`'s context. Basically, using the above example, you want something like this.

```javascript
const Parser = require('binary-parser').Parser;
const moment = require('moment');
Parser.prototype.$imports = {
    moment: moment
};

let time = function(timestamp) {
    return this.$imports.moment(timestamp, 'YYMMDDHHmmssSS').format('YYYY-MM-DD HH:mm:ss.SS');
};

let Telegram = new Parser().string('timestamp', { encoding: 'hex', length: 7, formatter: time });
```

You can use this approach to inject pretty much whatever you want in there.

**Comment by p0358** [comment]
Here's what appears to be possible, if you want to add a property to specific Parser object, and not a global:
```js
let opts = parser.encoderOpts;
opts.test = "test";
parser.encoderSetOptions(opts);

parser = parser.array(name, {
    /* ... */
    formatter: item => this.encoderOpts.test
});
```
(this would replace all objects there to "test", but it shows that it's indeed accessible this way)

**Comment by p0358** [comment]
NVM, it still appears to be global for the whole parser. Fuck me...
